id: P003004
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W4615
  title: གསུང་འབུམ། བློ་བཟང་འཕྲིན་ལས་བསྟན་པ་རྒྱ་མཚོ
  author: ''
  volumes:
    27bc51cc7e184b669f42ce383f0c30cc:
      image_group_id: I2232
      title: ''
      volume_number: 9
      total_pages: 818
      base_file: v001.txt
    81d500f555614b5782eb55e441d37652:
      image_group_id: I2233
      title: ''
      volume_number: 1
      total_pages: 808
      base_file: v002.txt
    bdc974b0fde04cb7ae5936432aec9eda:
      image_group_id: I2234
      title: ''
      volume_number: 2
      total_pages: 860
      base_file: v003.txt
    3f8b5b6bc3b2401abbc11702c00b9252:
      image_group_id: I2235
      title: ''
      volume_number: 3
      total_pages: 714
      base_file: v004.txt
    2df08a93ed154e1aa46540db6251c503:
      image_group_id: I2236
      title: ''
      volume_number: 4
      total_pages: 638
      base_file: v005.txt
    13a673f2949e48c7a264d6c6c6ad154f:
      image_group_id: I2237
      title: ''
      volume_number: 5
      total_pages: 1068
      base_file: v006.txt
    b017eb8678dd4d049ddb151f1dbfbbc3:
      image_group_id: I2238
      title: ''
      volume_number: 6
      total_pages: 847
      base_file: v007.txt
    25bd2176934446f392f0307932f03361:
      image_group_id: I2239
      title: ''
      volume_number: 7
      total_pages: 792
      base_file: v008.txt
    7604d9b560b6495eae7a71b6ac21f4c0:
      image_group_id: I2240
      title: ''
      volume_number: 8
      total_pages: 762
      base_file: v009.txt
    264c49fc26f0405aa4bb34581ba1444d:
      image_group_id: I2241
      title: ''
      volume_number: 10
      total_pages: 887
      base_file: v010.txt
    351696d29f284ddd81f2a195fd9e264e:
      image_group_id: I2242
      title: ''
      volume_number: 11
      total_pages: 318
      base_file: v011.txt
    16834ff9b8e54a89bfb4b7453c6eefee:
      image_group_id: I2243
      title: ''
      volume_number: 12
      total_pages: 454
      base_file: v012.txt
