id: I9514A608
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:02:36+00:00'
last_modified: '2022-06-07T16:56:10.808743+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4615
  title: གསུང་འབུམ། བློ་བཟང་འཕྲིན་ལས་བསྟན་པ་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C34C:
      image_group_id: I2233
      title: ''
      total_pages: 808
      order: 1
      base_file: C34C.txt
    5BB5:
      image_group_id: I2234
      title: ''
      total_pages: 860
      order: 2
      base_file: 5BB5.txt
    1DF6:
      image_group_id: I2235
      title: ''
      total_pages: 714
      order: 3
      base_file: 1DF6.txt
    20F0:
      image_group_id: I2236
      title: ''
      total_pages: 638
      order: 4
      base_file: 20F0.txt
    B142:
      image_group_id: I2237
      title: ''
      total_pages: 1068
      order: 5
      base_file: B142.txt
    5F74:
      image_group_id: I2238
      title: ''
      total_pages: 847
      order: 6
      base_file: 5F74.txt
    E060:
      image_group_id: I2239
      title: ''
      total_pages: 792
      order: 7
      base_file: E060.txt
    78E7:
      image_group_id: I2240
      title: ''
      total_pages: 762
      order: 8
      base_file: 78E7.txt
    A036:
      image_group_id: I2232
      title: ''
      total_pages: 818
      order: 9
      base_file: A036.txt
    '1644':
      image_group_id: I2241
      title: ''
      total_pages: 887
      order: 10
      base_file: 1644.txt
    B477:
      image_group_id: I2242
      title: ''
      total_pages: 318
      order: 11
      base_file: B477.txt
    462C:
      image_group_id: I2243
      title: ''
      total_pages: 454
      order: 12
      base_file: 462C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
